[build-system]
requires = [ "setuptools", "wheel",]
build-backend = "setuptools.build_meta"

[project]
name = "hyperion-ml"
version = "0.4.0a"
description = "Toolkit for speaker recognition"
readme = "README.md"
keywords = [ "speaker recognition", "adversarial attacks", "NIST SRE", "x-vectors",]
requires-python = ">=3.7"
dependencies = [ "torch>=1.9.0", "numpy>=1.18.1", "h5py>=2.10.0", "pysoundfile>=0.9.0", "matplotlib>=3.1.3", "pandas>=1.0.1", "scikit-learn>=0.22.1", "scipy>=1.4.1", "sphinx_rtd_theme>=0.4.3", "pympler", "memory_profiler", "gdown", "fairscale==0.4.4", "tensorboard>=2.5.0", "jsonargparse>=3.5.0", "wandb>=0.10.30", "librosa>=0.8.1", "isort", "black", "twine", "wheel", "transformers>=4.16.2", "sentencepiece>=0.1.97", "loralib", "lhotse>=1.23.0", "datasets>=2.20.0", "pytest", "toml", "kaldialign>=0.9.1", "utmosv2 @ git+https://github.com/jesus-villalba/UTMOSv2.git",]
[[project.authors]]
name = "Jesus Villalba"
email = "jesus.antonio.villalba@gmail.com"

[project.license]
text = "Apache-2.0"

[project.urls]
Homepage = "https://github.com/hyperion-ml/hyperion"

[project.scripts]
hyperion-finetune-xvector-from-feats = "hyperion.bin.finetune_xvector_from_feats:main"
hyperion-extract-wav2xvectors = "hyperion.bin.extract_wav2xvectors:main"
hyperion-train-plda = "hyperion.bin.train_plda:main"
hyperion-train-wav2vec2transducer = "hyperion.bin.train_wav2vec2transducer:main"
hyperion-eval-xvec-cosine-scoring-from-art-test-wav = "hyperion.bin.eval_xvec_cosine_scoring_from_art_test_wav:main"
hyperion-finetune-xvector-dfr-from-wav = "hyperion.bin.finetune_xvector_dfr_from_wav:main"
hyperion-decode-wav2transducer = "hyperion.bin.decode_wav2transducer:main"
hyperion-extract-xvectors-slidwin-from-feats = "hyperion.bin.extract_xvectors_slidwin_from_feats:main"
hyperion-make-babble-noise-audio-files = "hyperion.bin.make_babble_noise_audio_files:main"
hyperion-finetune-wav2xvector = "hyperion.bin.finetune_wav2xvector:main"
hyperion-finetune-wav2vec2xvector = "hyperion.bin.finetune_wav2vec2xvector:main"
hyperion-make-wav2xvector = "hyperion.bin.make_wav2xvector:main"
hyperion-pack-wav-rirs = "hyperion.bin.pack_wav_rirs:main"
hyperion-train-qmf = "hyperion.bin.train_qmf:main"
hyperion-compute-mfcc-feats = "hyperion.bin.compute_mfcc_feats:main"
hyperion-eval-xvec-cosine-scoring-from-transfer-art-test-wav = "hyperion.bin.eval_xvec_cosine_scoring_from_transfer_art_test_wav:main"
hyperion-prepare-data = "hyperion.bin.prepare_data:main"
hyperion-generate-adv-attacks-xvector-classif = "hyperion.bin.generate_adv_attacks_xvector_classif:main"
hyperion-train-lgbe = "hyperion.bin.train_lgbe:main"
hyperion-accum-speech-quality-metrics = "hyperion.bin.accum_speech_quality_metrics:main"
hyperion-train-wav2vec2rnn-transducer = "hyperion.bin.train_wav2vec2rnn_transducer:main"
hyperion-eval-xvec-logits-from-wav = "hyperion.bin.eval_xvec_logits_from_wav:main"
hyperion-train-xvector-from-feats = "hyperion.bin.train_xvector_from_feats:main"
hyperion-finetune-wav2vec2transducer = "hyperion.bin.finetune_wav2vec2transducer:main"
hyperion-decode-wav2vec2rnn-transducer = "hyperion.bin.decode_wav2vec2rnn_transducer:main"
hyperion-finetune-xvector-from-wav = "hyperion.bin.finetune_xvector_from_wav:main"
hyperion-plot-embedding-tsne = "hyperion.bin.plot_embedding_tsne:main"
hyperion-eval-wav2xvector-logits = "hyperion.bin.eval_wav2xvector_logits:main"
hyperion-extract-xvectors-from-wav = "hyperion.bin.extract_xvectors_from_wav:main"
hyperion-merge-scores = "hyperion.bin.merge_scores:main"
hyperion-adv-finetune-xvector-from-wav = "hyperion.bin.adv_finetune_xvector_from_wav:main"
hyperion-audio-to-duration = "hyperion.bin.audio_to_duration:main"
hyperion-eval-speech-quality-metrics = "hyperion.bin.eval_speech_quality_metrics:main"
hyperion-split-dataset-into-trials-and-cohort = "hyperion.bin.split_dataset_into_trials_and_cohort:main"
hyperion-copy-feats = "hyperion.bin.copy_feats:main"
hyperion-train-dino-wav2xvector = "hyperion.bin.train_dino_wav2xvector:main"
hyperion-eval-verification-calibration = "hyperion.bin.eval_verification_calibration:main"
hyperion-eval-lgbe = "hyperion.bin.eval_lgbe:main"
hyperion-compute-energy-vad = "hyperion.bin.compute_energy_vad:main"
hyperion-apply-mvn-select-frames = "hyperion.bin.apply_mvn_select_frames:main"
hyperion-tables = "hyperion.bin.hyperion_tables:main"
hyperion-train-wav2xvector = "hyperion.bin.train_wav2xvector:main"
hyperion-eval-wav2vec2xvector-logits = "hyperion.bin.eval_wav2vec2xvector_logits:main"
hyperion-train-verification-calibration = "hyperion.bin.train_verification_calibration:main"
hyperion-eval-cosine-scoring-backend-with-qmf = "hyperion.bin.eval_cosine_scoring_backend_with_qmf:main"
hyperion-train-xvector-from-wav = "hyperion.bin.train_xvector_from_wav:main"
hyperion-train-verification-greedy-fusion = "hyperion.bin.train_verification_greedy_fusion:main"
hyperion-train-tokenizer = "hyperion.bin.train_tokenizer:main"
hyperion-extract-xvectors-from-feats = "hyperion.bin.extract_xvectors_from_feats:main"
hyperion-eval-plda-backend = "hyperion.bin.eval_plda_backend:main"
hyperion-merge-trials = "hyperion.bin.merge_trials:main"
hyperion-train-wav2rnn-transducer = "hyperion.bin.train_wav2rnn_transducer:main"
hyperion-preprocess-audio-files = "hyperion.bin.preprocess_audio_files:main"
hyperion-eval-xvec-cosine-scoring-from-adv-test-wav-wavegan = "hyperion.bin.eval_xvec_cosine_scoring_from_adv_test_wav_wavegan:main"
hyperion-finetune-xvector-dfr-from-feats = "hyperion.bin.finetune_xvector_dfr_from_feats:main"
hyperion-train-wav2vec2xvector = "hyperion.bin.train_wav2vec2xvector:main"
hyperion-eval-verification-anonymization-metrics = "hyperion.bin.eval_verification_anonymization_metrics:main"
hyperion-eval-verification-metrics = "hyperion.bin.eval_verification_metrics:main"
hyperion-eval-cosine-scoring-backend = "hyperion.bin.eval_cosine_scoring_backend:main"
hyperion-plot-embedding-tsne-per-class = "hyperion.bin.plot_embedding_tsne_per_class:main"
hyperion-generate-adv-attacks-xvector-verif = "hyperion.bin.generate_adv_attacks_xvector_verif:main"
hyperion-eval-xvec-cosine-scoring-from-adv-test-wav = "hyperion.bin.eval_xvec_cosine_scoring_from_adv_test_wav:main"
hyperion-dataset = "hyperion.bin.hyperion_dataset:main"
hyperion-convert-vad-format = "hyperion.bin.convert_vad_format:main"
hyperion-eval-xvec-cosine-scoring-from-transfer-adv-test-wav = "hyperion.bin.eval_xvec_cosine_scoring_from_transfer_adv_test_wav:main"
hyperion-eval-verification-greedy-fusion = "hyperion.bin.eval_verification_greedy_fusion:main"
hyperion-eval-xvec-cosine-scoring-from-test-wav = "hyperion.bin.eval_xvec_cosine_scoring_from_test_wav:main"
hyperion-extract-xvectors-slidwin-from-wav = "hyperion.bin.extract_xvectors_slidwin_from_wav:main"
hyperion-extract-wav2vec2xvectors = "hyperion.bin.extract_wav2vec2xvectors:main"
hyperion-cluster-embeddings = "hyperion.bin.cluster_embeddings:main"

[tool.setuptools.packages.find]
exclude = [ "tests",]
