data:
  train:
    dataset:
      class_names:
      - speaker
      aug_cfgs:
      - conf/reverb_noise_tel_codecs_1_aug.yaml
      enable_tel_codecs_if: "source_type != 'cts'"
      return_segment_info:
      - speaker
      target_sample_freq: 16000
      wav_scale: 1
    sampler:
      sampler_type: seg_chunk_sampler
      min_batch_size: 32
      max_chunk_length: 3.0
      min_chunk_length: 3.0
      class_name: speaker
      max_batches_per_epoch: 5000
    data_loader:
      num_workers: 8
  val:
    dataset:
      class_names:
      - speaker
      aug_cfgs:
      - conf/reverb_noise_tel_codecs_1_aug.yaml
      enable_tel_codecs_if: "source_type != 'cts'"
      return_segment_info:
      - speaker
      target_sample_freq: 16000
      wav_scale: 1
    sampler:
      sampler_type: class_weighted_random_seg_chunk_sampler
      # min_batch_size: 32
      min_batch_size: 128
      max_chunk_length: 2.0
      min_chunk_length: 2.0
      num_chunks_per_seg_epoch: 2
      class_name: speaker
      seg_weight_mode: uniform
      # sampler_type: seg_chunk_sampler
      # min_batch_size: 32
      # max_chunk_length: 3.0
      # min_chunk_length: 3.0
      # class_name: speaker
    data_loader:
      num_workers: 8
model:
  xvector:
    override_output: true
    cos_scale: 32.0
    margin: 0.2
    margin_warmup_epochs: 0
    intertop_k: 5
    intertop_margin: 0.1
trainer: 
  optim:
    opt_type: sgd
    lr: 5e-3
    momentum: 0.9
    weight_decay: 1e-4
  lrsched:
    lrsch_type: exp_lr
    decay_rate: 0.5
    decay_steps: 5000
    hold_steps: 6000
    min_lr: 5e-5
    warmup_steps: 6000
    update_lr_on_opt_step: true
  use_amp: true
  log_interval: 1000
  epochs: 100
  eff_batch_size: 512
  target_key: speaker
  train_mode: full
master_port: 3434
