data:
  train:
    dataset:
      class_names:
      - speaker
      aug_cfgs:
      - conf/reverb_noise_tel_codecs_1_aug.yaml
      enable_tel_codecs_if: "source_type != 'cts'"
      return_segment_info:
      - speaker
      wav_scale: 1.
      target_sample_freq: 16000
    sampler:
      sampler_type: class_weighted_random_seg_chunk_sampler
      min_batch_size: 16
      max_chunk_length: 8.0
      min_chunk_length: 8.0
      num_chunks_per_seg_epoch: 1
      class_name: speaker
      # weight_exponent: 0.5
      # weight_mode: data-prior
      seg_weight_mode: data-prior
      num_hard_prototypes: 8
    data_loader:
      num_workers: 8
  val:
    dataset:
      class_names:
      - speaker
      aug_cfgs:
      - conf/reverb_noise_tel_codecs_1_aug.yaml
      enable_tel_codecs_if: "source_type != 'cts'"
      return_segment_info:
      - speaker
      num_augs: 1
      wav_scale: 1.
      target_sample_freq: 16000
    sampler:
      sampler_type: class_weighted_random_seg_chunk_sampler
      # min_batch_size: 32
      min_batch_size: 128
      max_chunk_length: 2.0
      min_chunk_length: 2.0
      num_chunks_per_seg_epoch: 2
      class_name: speaker
      seg_weight_mode: uniform
      # sampler_type: seg_chunk_sampler
      # min_batch_size: 32
      # max_chunk_length: 3.0
      # min_chunk_length: 3.0
      # class_name: speaker
      # sampler_type: class_weighted_random_seg_chunk_sampler
      # min_batch_size: 16
      # max_chunk_length: 3.0
      # min_chunk_length: 3.0
      # num_chunks_per_seg_epoch: 6
      # class_name: speaker
      # weight_exponent: 0.5
      # weight_mode: data-prior
      # seg_weight_mode: data-prior
      # num_hard_prototypes: 0
    data_loader:
      num_workers: 8
model:
  xvector:
    override_output: true
    cos_scale: 32.0
    margin: 0.4
    margin_warmup_epochs: 3
    intertop_margin: 0.1
    override_dropouts: true
    dropout_rate: 0.0
trainer:
  optim:
    opt_type: sgd
    lr: 0.001
    momentum: 0.9
    weight_decay: 2e-5
  lrsched:
    lrsch_type: cos_lr
    t: 2500
    t_mul: 2
    warm_restarts: true
    gamma: 0.75
    min_lr: 1e-4
    warmup_steps: 100
    update_lr_on_opt_step: true
  grad_clip: 250
  use_amp: true
  log_interval: 1000
  epochs: 7
  eff_batch_size: 128
  swa_start: 20
  swa_lr: 1e-4
  swa_anneal_epochs: 2
  target_key: speaker
  train_mode: full
master_port: 8765
