data:
  train:
    dataset:
      class_names:
      - speaker
      aug_cfgs:
      - conf/reverb_noise_aug.yaml
      return_segment_info:
      - speaker
      num_augs: 4
    sampler:
      sampler_type: seg_chunk_sampler
      min_batch_size: 64
      max_chunk_length: 2.0
      min_chunk_length: 2.0
    data_loader:
      num_workers: 8
  val:
    dataset:
      class_names:
      - speaker
      aug_cfgs:
      - conf/reverb_noise_aug.yaml
      return_segment_info:
      - speaker
    sampler:
      sampler_type: seg_chunk_sampler
      min_batch_size: 64
      max_chunk_length: 2.0
      min_chunk_length: 2.0
    data_loader:
      num_workers: 8
model:
  feats: fbank80_specaug1_stmn_16k.yaml
  xvector:
    resnet_enc:
      in_feats: 80
      in_conv_channels: 512
      in_kernel_size: 5
      in_stride: 1
      resb_type: seres2bn
      resb_repeats:
      - 1
      - 1
      - 1
      resb_channels:
      - 512
      resb_kernel_sizes:
      - 3
      resb_dilations:
      - 2
      - 3
      - 4
      resb_strides:
      - 1
      res2net_width_factor: 1
      res2net_scale: 8
      se_r: 4
      multilayer: true
      multilayer_concat: true
      endpoint_channels: 1536
      norm_before: false
      dropout_rate: 0.002
      hid_act: swish
    pool_net:
      pool_type: ch-wise-att-mean+stddev
      inner_feats: 128
    embed_dim: 192
    cos_scale: 30.0
    loss_type: subcenter-arc-softmax
    num_subcenters: 2
    margin: 0.2
    margin_warmup_epochs: 5.0
    dropout_rate: 0.0
    norm_before: false
    hid_act: swish
trainer:
  optim: 
    opt_type: adam
    lr: 0.01
    amsgrad: true
    beta1: 0.9
    beta2: 0.99
    weight_decay: 2.0e-05
  lrsched:
    lrsch_type: exp_lr
    decay_rate: 0.5
    decay_steps: 40000
    hold_steps: 65000
    min_lr: 1.0e-05
    warmup_steps: 15000
    update_lr_on_opt_step: true
  grad_clip: 250
  use_amp: true
  log_interval: 1000
  epochs: 40
  eff_batch_size: 256
  target_key: speaker
  train_mode: full
