dataset:
  dataset:
    class_names:
    - class_id
    aug_cfgs:
    - conf/reverb_noise_aug.yaml
    return_segment_info:
    - class_id
  sampler:
    sampler_type: class_weighted_random_seg_chunk_sampler
    min_batch_size: 32
    max_chunk_length: 4.0
    min_chunk_length: 4.0
    num_chunks_per_seg_epoch: 6
    class_name: class_id
    seg_weight_mode: uniform
    num_hard_prototypes: 0
  data_loader:
    num_workers: 8
