data:
  train:
    dataset:
      class_names:
      - spoof_det
      aug_cfgs:
      - conf/reverb_noise_aug.yaml
      return_segment_info:
      - spoof_det
      num_augs: 6
    sampler:
      sampler_type: seg_chunk_sampler
      min_batch_size: 64
      max_chunk_length: 2.0
      min_chunk_length: 2.0
    data_loader:
      num_workers: 8
  val:
    dataset:
      class_names:
      - spoof_det
      return_segment_info:
      - spoof_det
    sampler:
      sampler_type: bucketing_seg_sampler
      max_batch_length: 100.
    data_loader:
      num_workers: 8
model:
  feats: fbank80_specaug1_stmn_16k.yaml
  xvector:
    resnet_type: lresnet34
    in_channels: 1
    in_feats: 80
    in_kernel_size: 3
    in_stride: 1
    no_maxpool: true
    pool_net:
      pool_type: ch-wise-att-mean+stddev
      inner_feats: 128
    embed_dim: 192
    loss_type: subcenter-arc-softmax
    num_subcenters: 2
    cos_scale: 30.0
    margin: 0.2
    margin_warmup_epochs: 5.0
    dropout_rate: 0.1
    norm_before: false
    hid_act: swish
trainer:
  optim: 
    opt_type: adamw
    lr: 0.001
    amsgrad: false
    beta1: 0.9
    beta2: 0.99
    weight_decay: 0.1
  lrsched:
    lrsch_type: exp_lr
    decay_rate: 0.5
    decay_steps: 3000
    hold_steps: 3000
    min_lr: 1.0e-05
    warmup_steps: 1500
    update_lr_on_opt_step: true
  grad_clip: 250
  use_amp: true
  log_interval: 1000
  epochs: 100
  eff_batch_size: 256
  target_key: spoof_det
master_port: 5678
