data:
  train:
    dataset:
      wav_scale: 1
      aug_cfgs: 
        - conf/reverb_noise_aug.yaml
      return_segment_info:
        - text
        - language
    sampler:
      #sampler_type: 'bucketing_seg_sampler'
      sampler_type: 'class_weighted_random_bucketing_seg_sampler'
      max_batch_length: 15.
      max_audio_length: 15.
      min_batch_size: 1
      drop_last: false
      # for class_weighted_random_bucketing_seg_sampler
      base_sampler_type: class_weighted_seg_sampler
      weight_mode: "data-prior"
      class_name: "language"
      weight_exponent: 0.3
      num_chunks_per_seg_epoch: 0.05

    data_loader:
      num_workers: 8
  val:
    dataset:
      aug_cfgs: 
        - conf/reverb_noise_aug.yaml
      wav_scale: 1
      return_segment_info:
        - text
        - language
    sampler:
      #sampler_type: 'bucketing_seg_sampler'
      sampler_type: 'class_weighted_random_bucketing_seg_sampler'
      max_batch_length: 15.
      max_audio_length: 15.
      min_batch_size: 1
      drop_last: true
      # for class_weighted_random_bucketing_seg_sampler
      base_sampler_type: class_weighted_seg_sampler
      weight_mode: "data-prior"
      class_name: "language"
      weight_exponent: 0.3
      num_chunks_per_seg_epoch: 1.0
    data_loader:
      num_workers: 8
model:
  hf_feats:
    pretrained_model_path: facebook/wav2vec2-xls-r-300m   
  transducer:
    decoder:
      film_cond_type: lid_pred
      reduction: mean
      prune_range: 15
      rnnt_loss: k2_pruned
      simple_loss_scale: 0.2
      condition_size: 256
      predictor:
        embed_dim: 1024
        num_layers: 2
        hid_feats: 512
        embed_dropout_rate: 0.4
        rnn_dropout_rate: 0.4
        rnn_type: lstm_residual
      joiner:
        hid_feats: 512
  languageid:
    resnet_enc:
      in_feats: 1024
      in_conv_channels: 1024
      in_kernel_size: 5
      in_stride: 1
      resb_type: seres2bn
      resb_repeats:
        - 1
      resb_channels:
        - 512
      resb_kernel_sizes:
        - 3
      resb_dilations:
        - 2
      resb_strides:
        - 1
      res2net_width_factor: 1
      res2net_scale: 8
      se_r: 8
      multilayer: true
      multilayer_concat: true
      endpoint_channels: 3072
      hid_act: swish
      dropout_rate: 0.2
    pool_net:
      pool_type: ch-wise-att-mean+stddev
      inner_feats: 128
    embed_dim: 128
    loss_type: arc-softmax
    cos_scale: 32.0
    margin: 0.
    margin_warmup_epochs: 5
    intertop_margin: 0.
    dropout_rate: 0.3
    hid_act: swish

  loss_lid_type: weightedCE
  loss_class_weight_exp: 1.0 # 0~1

  loss_weight_transducer: 0.1
  loss_weight_lid: 1.0
  lid_length: 3.0
  
  feat_fusion_method_transducer: film-weighted-avg
  feat_fusion_method_lid: weighted-avg
  feat_fusion_start_transducer: 2
  feat_fusion_start_lid: 2

trainer:
  optim:
    opt_type: sgd
    lr: 0.0002
    momentum: 0.9
    weight_decay: 4e-4
  lrsched:
    lrsch_type: exp_lr
    decay_rate: 0.5
    decay_steps: 180000
    hold_steps: 60000
    min_lr: 4e-5
    warmup_steps: 6000
    update_lr_on_opt_step: true
  grad_clip: 100
  use_amp: true
  log_interval: 1000
  epochs: 120
  # eff_batch_size: 1024
  eff_batch_size: 128
  train_mode: full
 