data:
  train:
    dataset:
      aug_cfgs:
      - conf/reverb_noise_aug.yaml
      return_segment_info:
      - language
      target_sample_freq: 16000
      wav_scale: 1
    sampler:
      sampler_type: 'class_weighted_random_seg_chunk_sampler'
      min_batch_size: 24 
      max_chunk_length: 3.0
      min_chunk_length: 3.0
      # weighted
      weight_mode: "data-prior"
      class_name: "language"
      weight_exponent: 0.3
      num_chunks_per_seg_epoch: 0.2
    data_loader:
      num_workers: 8
  val:
    dataset:
      aug_cfgs:
      - conf/reverb_noise_aug.yaml
      return_segment_info:
      - language
      target_sample_freq: 16000
      wav_scale: 1
    sampler:
      sampler_type: 'class_weighted_random_seg_chunk_sampler'
      min_batch_size: 24 
      max_chunk_length: 3.0
      min_chunk_length: 3.0
      # weighted
      weight_mode: "data-prior"
      class_name: "language"
      weight_exponent: 0.3
      num_chunks_per_seg_epoch: 1.0
    data_loader:
      num_workers: 8
model:
  languageid:
    cos_scale: 32.0
trainer:
  optim:
    opt_type: sgd
    lr: 0.0005
    momentum: 0.9
    weight_decay: 4e-4
  lrsched:
    lrsch_type: exp_lr
    decay_rate: 0.5
    #decay_steps: 4200
    #hold_steps: 1500
    decay_steps: 16000
    hold_steps: 32000
    min_lr: 4e-4
    warmup_steps: 5000
    update_lr_on_opt_step: true
  use_amp: true
  log_interval: 1000
  epochs: 100
  eff_batch_size: 1024
  train_mode: full

 