data:
  train:
    dataset:
      wav_scale: 1
      aug_cfgs: 
        - conf/reverb_noise_aug.yaml
      return_segment_info:
        - language
    sampler:
      #sampler_type: 'seg_sampler'
      sampler_type: 'bucketing_seg_sampler'
      max_batch_length: 85.
      min_batch_size: 2
      drop_last: false
    data_loader:
      num_workers: 1
  val:
    dataset:
      aug_cfgs: 
        - conf/reverb_noise_aug.yaml
      wav_scale: 1
      return_segment_info:
        - language
    sampler:
      #sampler_type: 'seg_sampler'
      sampler_type: 'bucketing_seg_sampler'
      max_batch_length: 30
      min_batch_size: 2
      drop_last: true
    data_loader:
      num_workers: 1
model: wav2vec2xlsr300m_ecapatdnn512x3.yaml
trainer:
  optim:
    opt_type: sgd
    lr: 0.003
    momentum: 0.9
    weight_decay: 4e-4
  lrsched:
    lrsch_type: exp_lr
    decay_rate: 0.5
    decay_steps: 4200
    hold_steps: 1500
    min_lr: 4e-5
    warmup_steps: 1500
    update_lr_on_opt_step: true
  grad_clip: 100
  use_amp: true
  log_interval: 1000
  epochs: 120
  # eff_batch_size: 1024
  eff_batch_size: 128
  train_mode: hf-feats-frozen-nograd

 
