dataset:
  max_chunk_length: 2.0
  min_chunk_length: 2.0
  aug_cfg: conf/reverb_noise_aug.yaml 
sampler:
  batch_size: 48 # 52:64:4 OOM w/ lresnet34 in this version of hyperion (It wasn't in the old version).
  iters_per_epoch: 1
data_loader:
  num_workers: 8
  
