data:
  train:
    dataset:
      class_names:
      - class_id
      aug_cfgs:
      - conf/reverb_noise_aug.yaml
      return_segment_info:
      - class_id
      target_sample_freq: 16000
      wav_scale: 1
    sampler:
      sampler_type: seg_chunk_sampler
      min_batch_size: 128
      max_chunk_length: 3.0
      min_chunk_length: 3.0
      class_name: class_id
    data_loader:
      num_workers: 8
  val:
    dataset:
      class_names:
      - class_id
      aug_cfgs:
      - conf/reverb_noise_aug.yaml
      return_segment_info:
      - class_id
      target_sample_freq: 16000
      wav_scale: 1
    sampler:
      sampler_type: seg_chunk_sampler
      min_batch_size: 128
      max_chunk_length: 3.0
      min_chunk_length: 3.0
      class_name: class_id
    data_loader:
      num_workers: 8
model: wavlmlarge_ecapatdnn512x3_v2.0.yaml
trainer:
  optim:
    opt_type: sgd
    lr: 0.4
    momentum: 0.9
    weight_decay: 4e-4
  lrsched:
    lrsch_type: exp_lr
    decay_rate: 0.5
    decay_steps: 7500
    hold_steps: 2600
    #min_lr: 4e-4
    min_lr: 1e-6
    warmup_steps: 2600
    update_lr_on_opt_step: true
  use_amp: true
  log_interval: 1000
  epochs: 35
  eff_batch_size: 1024
  train_mode: hf-feats-frozen-nograd
 