data:
  train:
    dataset:
      class_names:
      - class_id
      aug_cfgs:
      - conf/reverb_noise_aug.yaml
      return_segment_info:
      - class_id
      target_sample_freq: 16000
      wav_scale: 1
    sampler:
      sampler_type: class_weighted_random_seg_chunk_sampler
      min_batch_size: 32
      max_chunk_length: 3.0
      min_chunk_length: 3.0
      num_chunks_per_seg_epoch: 6
      class_name: class_id
      seg_weight_mode: uniform
      num_hard_prototypes: 0
    data_loader:
      num_workers: 8
  val:
    dataset:
      class_names:
      - class_id
      aug_cfgs:
      - conf/reverb_noise_aug.yaml
      return_segment_info:
      - class_id
      target_sample_freq: 16000
      wav_scale: 1
    sampler:
      sampler_type: class_weighted_random_seg_chunk_sampler
      min_batch_size: 32
      max_chunk_length: 4.0
      min_chunk_length: 4.0
      num_chunks_per_seg_epoch: 6
      class_name: class_id
      seg_weight_mode: uniform
      num_hard_prototypes: 0
    data_loader:
      num_workers: 8
model: wavlmlarge6l_ecapatdnn512x3.yaml
trainer:
  optim:
    opt_type: sgd
    lr: 0.45
    momentum: 0.9
    weight_decay: 4e-4
  lrsched:
    lrsch_type: exp_lr
    decay_rate: 0.5
    decay_steps: 4200
    hold_steps: 1500
    min_lr: 4e-4
    warmup_steps: 1500
    update_lr_on_opt_step: true
  use_amp: true
  log_interval: 1000
  epochs: 60
  eff_batch_size: 1024
  train_mode: hf-feats-frozen-nograd

 