feats: fbank80_stmn_16k.yaml
min_chunk_length: 4
max_chunk_length: 4
iters_per_epoch: 6
resnet_type: lresnet34
in_feats: 80
in_channels: 1
in_kernel_size: 3
in_stride: 1
no_maxpool: true
dropout_rate: 0.0
embed_dim: 10
margin: 0.2
margin_warmup_epochs: 6.0
s: 30
epochs: 20
optim:
  amsgrad: true
  beta1: 0.9
  beta2: 0.95
  lr: 0.01
  opt_type: adam
  weight_decay: 1.0e-05
lrsched:
  decay_rate: 0.5
  decay_steps: 8000
  eps: 1.0e-08
  hold_steps: 16000
  lrsch_type: exp_lr
  min_lr: 1.0e-05
  update_lr_on_opt_step: true
  warmup_steps: 1000
