data:
  train:
    dataset:
      class_names:
      - class_id
      return_segment_info:
      - class_id
    sampler:
      sampler_type: class_weighted_random_seg_chunk_sampler
      min_batch_size: 16
      max_chunk_length: 4.0
      min_chunk_length: 4.0
      num_chunks_per_seg_epoch: 6
      class_name: class_id
    data_loader:
      num_workers: 8
  val:
    dataset:
      class_names:
      - class_id
      return_segment_info:
      - class_id
    sampler:
      sampler_type: class_weighted_random_seg_chunk_sampler
      min_batch_size: 64
      max_chunk_length: 4.0
      min_chunk_length: 4.0
      num_chunks_per_seg_epoch: 6
      class_name: class_id
    data_loader:
      num_workers: 8
feats: fbank80_stmn_16k.yaml
model:
  resnet_type: res2net50
  in_feats: 80
  in_channels: 1
  in_kernel_size: 3
  in_stride: 1
  no_maxpool: true
  res2net_width_factor: 1.625
  res2net_scale: 4
  dropout_rate: 0.0
  embed_dim: 10
  margin: 0.2
  margin_warmup_epochs: 6.0
  s: 30
trainer:
  epochs: 20
  eff_batch_size: 256
  optim:
    amsgrad: true
    beta1: 0.9
    beta2: 0.95
    lr: 0.01
    opt_type: adam
    weight_decay: 1.0e-05
  lrsched:
    decay_rate: 0.5
    decay_steps: 8000
    eps: 1.0e-08
    hold_steps: 16000
    lrsch_type: exp_lr
    min_lr: 1.0e-05
    update_lr_on_opt_step: true
    warmup_steps: 1000
