data:
  train:
    dataset:
      class_names:
      - class_id
      aug_cfgs:
      - conf/reverb_noise_aug.yaml
      return_segment_info:
      - class_id
    sampler:
      sampler_type: class_weighted_random_seg_chunk_sampler
      min_batch_size: 128
      max_chunk_length: 4.0
      min_chunk_length: 4.0
      num_chunks_per_seg_epoch: 1
      class_name: class_id
      seg_weight_mode: uniform
    data_loader:
      num_workers: 8
  val:
    dataset:
      class_names:
      - class_id
      aug_cfgs:
      - conf/reverb_noise_aug.yaml
      return_segment_info:
      - class_id
    sampler:
      sampler_type: class_weighted_random_seg_chunk_sampler
      min_batch_size: 128
      max_chunk_length: 4.0
      min_chunk_length: 4.0
      num_chunks_per_seg_epoch: 1
      class_name: class_id
      seg_weight_mode: uniform
    data_loader:
      num_workers: 8
feats: fbank64_stmn_nb_16k.yaml
model:
  resnet_type: lresnet34
  in_channels: 1
  in_feats: 64
  conv_channels: 64
  in_kernel_size: 3
  in_stride: 1
  in_norm: false
  no_maxpool: true
  pool_net:
    pool_type: ch-wise-att-mean+stddev
    inner_feats: 32
  embed_dim: 32
  num_embed_layers: 1
  hid_act: relu6
  loss_type: arc-softmax
  cos_scale: 30.0
  margin: 0.3
  margin_warmup_epochs: 30.0
  dropout_rate: 0.0
trainer:
  optim:
    opt_type: adam
    lr: 0.02
    beta1: 0.9
    beta2: 0.95
    amsgrad: true
    weight_decay: 1e-5
  lrsched:
    lrsch_type: exp_lr
    decay_rate: 0.5
    decay_steps: 8000
    hold_steps: 10000
    min_lr: 1.0e-05
    warmup_steps: 1000
    update_lr_on_opt_step: true
  epochs: 70
  log_interval: 100
  use_amp: true

