#!/usr/bin/env python3
"""Render the task-oriented CLI index from the command inventory."""

from __future__ import annotations

import json
import sys
from collections import defaultdict
from pathlib import Path


DOCS_DIR = Path(__file__).resolve().parent
INVENTORY_PATH = DOCS_DIR / "cli_inventory.json"
OUTPUT_PATH = DOCS_DIR / "generated" / "cli-index.rst"

FAMILY_ORDER = (
    "training",
    "fine_tuning",
    "extraction_inference",
    "backend_scoring_evaluation",
    "data_preparation",
    "format_conversion",
    "visualization_utilities",
)
FAMILY_TITLES = {
    "training": "Training",
    "fine_tuning": "Fine-tuning and adaptation",
    "extraction_inference": "Extraction and inference",
    "backend_scoring_evaluation": "Backends, scoring, and evaluation",
    "data_preparation": "Data preparation and manifest operations",
    "format_conversion": "Audio, feature, and VAD conversion",
    "visualization_utilities": "Visualization and utilities",
}


def format_command(command: dict[str, object]) -> str:
    """Format one command record as a compact RST list item."""
    optional = command["optional_requirements"]
    requirement_text = ""
    if optional:
        requirement_text = f" Conditional runtime requirements: {', '.join(optional)}."
    return f"* ``{command['command']}``{requirement_text}"


def render() -> str:
    """Render the generated command index."""
    inventory = json.loads(INVENTORY_PATH.read_text(encoding="utf-8"))
    grouped: dict[str, list[dict[str, object]]] = defaultdict(list)
    for command in inventory["commands"]:
        grouped[command["family"]].append(command)

    lines = [
        ".. This file is generated by docs/render_cli_index.py; do not edit it directly.",
        "",
    ]
    for family in FAMILY_ORDER:
        commands = sorted(grouped[family], key=lambda command: command["command"])
        lines.extend([FAMILY_TITLES[family], "~" * len(FAMILY_TITLES[family]), ""])
        guide = commands[0]["guide"][:-4]
        lines.extend(
            [
                inventory["families"][family],
                "",
                f"Read the :doc:`{FAMILY_TITLES[family].lower()} guide </{guide}>`.",
                "",
            ]
        )
        for status, label in (("stable", "Stable commands"), ("experimental", "Experimental commands")):
            selected = [command for command in commands if command["status"] == status]
            if not selected:
                continue
            lines.extend([f"{label}:", ""])
            lines.extend(format_command(command) for command in selected)
            lines.append("")
    return "\n".join(lines)


def main() -> int:
    """Write the generated command index or check it for drift."""
    content = render()
    if "--check" in sys.argv[1:]:
        if not OUTPUT_PATH.is_file() or OUTPUT_PATH.read_text(encoding="utf-8") != content:
            print("CLI index is stale; rerun docs/render_cli_index.py", file=sys.stderr)
            return 1
        return 0
    if len(sys.argv) != 1:
        print("usage: render_cli_index.py [--check]", file=sys.stderr)
        return 2
    OUTPUT_PATH.parent.mkdir(parents=True, exist_ok=True)
    OUTPUT_PATH.write_text(content, encoding="utf-8")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
