data:
  train:
    dataset:
      wav_scale: 1
      aug_cfgs: 
        - conf/reverb_noise_aug.yaml
      return_segment_info:
        - text
    sampler:
      sampler_type: 'bucketing_seg_sampler'
      max_batch_length: 75.
      min_batch_size: 1
      drop_last: false
    data_loader:
      num_workers: 4
  val:
    dataset:
      aug_cfgs: 
        - conf/reverb_noise_aug.yaml
      wav_scale: 1
      return_segment_info:
        - text
    sampler:
      sampler_type: 'bucketing_seg_sampler'
      max_batch_length: 75.
      min_batch_size: 1
      drop_last: true
    data_loader:
      num_workers: 4
model: wav2vec2base_transducer_do0.4.yaml
trainer:
  optim:
    opt_type: sgd
    lr: 0.003
    momentum: 0.9
    weight_decay: 4e-4
  lrsched:
    lrsch_type: exp_lr
    decay_rate: 0.5
    decay_steps: 42000
    hold_steps: 15000
    min_lr: 4e-5
    warmup_steps: 15000
    update_lr_on_opt_step: true
  grad_clip: 100
  use_amp: true
  log_interval: 1000
  epochs: 1200
  # eff_batch_size: 1024
  eff_batch_size: 128
  train_mode: hf-feats-frozen-nograd

 