data:
  train:
    dataset:
      wav_scale: 1
      aug_cfgs: 
        - conf/reverb_noise20dB_aug.yaml
      return_segment_info:
        - text
    sampler:
      sampler_type: bucketing_seg_sampler
      max_batch_length: 28.
      min_batch_size: 1
      drop_last: false
    data_loader:
      num_workers: 4
  val:
    dataset:
      aug_cfgs: 
        - conf/reverb_noise20dB_aug.yaml
      wav_scale: 1
      return_segment_info:
        - text
    sampler:
      sampler_type: bucketing_seg_sampler
      max_batch_length: 28.
      min_batch_size: 1
      drop_last: true
    data_loader:
      num_workers: 4
model: 
  hf_feats:
    pretrained_model_path: facebook/wav2vec2-base-960h
  transducer:
    encoder:
      att_type: block-scaled-dot-prod-v1
      att_context: 8
      d_model: 512
      num_heads: 8
      num_blocks: 1
      d_ff: 2048
      in_layer_type: linear
    decoder:
      rnnt_loss: k2_pruned
      simple_loss_scale: 0.2
      predictor:
        embed_dim: 1024
        num_layers: 2
        hid_feats: 512
        embed_dropout_rate: 0.4
        rnn_dropout_rate: 0.4
        rnn_type: lstm
      joiner:
        hid_feats: 512
  feat_fusion_method: weighted-avg
  feat_fusion_start: 2
trainer:
  optim:
    opt_type: adamw
    lr: 0.001
    beta1: 0.9
    beta2: 0.99
    weight_decay: 4e-4
  lrsched:
    lrsch_type: exp_lr
    decay_rate: 0.5
    decay_steps: 4200
    hold_steps: 1500
    min_lr: 4e-5
    warmup_steps: 1500
    update_lr_on_opt_step: true
  grad_clip: 100
  use_amp: true
  log_interval: 1000
  epochs: 120
  eff_batch_size: 128
  train_mode: hf-feats-frozen-nograd
